<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sp</string>
		<string>cdl</string>
		<string>mdl</string>
		<string>cir</string>
		<string>mod</string>
		<string>scs</string>
		<string>spi</string>
	</array>
	<key>name</key>
	<string>SPICE</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comments.</string>
			<key>match</key>
			<string>\*.*</string>
			<key>name</key>
			<string>comment.line.character.sp</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Voltage and current sources.</string>
			<key>match</key>
			<string>^([ \t])*//.*+</string>
			<key>name</key>
			<string>comment.line.character.sp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>comment</key>
			<string>Single quotes.</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.quoted.single.sp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>comment</key>
			<string>Double quotes.</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.sp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.sp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>SPECTRE specific commands</string>
			<key>match</key>
			<string>([\.]?(?i:tran|to|tf|temp|subckt|statistics|simulator|set|sens|section|process|probe|print|plot|parameters|param|option|op|noise|model|measure|meas|lib|let|include|ic|from|four|endsection|ends|endl|endc|end|disto|dc|control|alter|ac))[^a-zA-Z0-9_]</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>SPICEOPUS commands.</string>
			<key>match</key>
			<string>^[ \t]*[.]?(?i:destroy|plot)[^a-zA-Z0-9_]</string>
			<key>name</key>
			<string>keyword.control.sp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.sp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>command parameters</string>
			<key>match</key>
			<string>((?i:when|trig|tran|targ|find|deriv))[^a-zA-Z0-9_]</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.sp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Waveform functions</string>
			<key>match</key>
			<string>((?i:dc|pulse|pwl))[^a-zA-Z0-9_]</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.sp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Liberty parameters.</string>
			<key>match</key>
			<string>((?i:sin|cos|tan|asin|acos|atan|sinh|cosh|tanh|abs|sqrt|pow|pwr|log|log10|exp|db|int|sgn|sign|min|max|lv|lx|v|i))[^a-zA-Z0-9_]</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Voltage and current sources.</string>
			<key>match</key>
			<string>^[ \t]*(?i:v|i|e|g|h|f)[a-zA-Z0-9_@]+</string>
			<key>name</key>
			<string>entity.name.tag.sp</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Built-in devices.</string>
			<key>match</key>
			<string>^[ \t]*(?i:m|r|c|l|k|s|w)[a-zA-Z0-9_@]+</string>
			<key>name</key>
			<string>support.type.sp</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Sub circuits.</string>
			<key>match</key>
			<string>^[ \t]*(?i:x)[a-zA-Z0-9_@]+</string>
			<key>name</key>
			<string>entity.sp</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Break line symbol at begin of line</string>
			<key>match</key>
			<string>^[ \t]*\+</string>
			<key>name</key>
			<string>string.quoted.single.sp</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>At end of line</string>
			<key>match</key>
			<string>\+[ \t]$</string>
			<key>name</key>
			<string>string.quoted.single.sp</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.sp</string>
	<key>uuid</key>
	<string>b46f7485-a428-48e8-a1f8-05e3afb64e0a</string>
</dict>
</plist>
